name = "signals-workshop-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# Secrets (set these via: wrangler secret put <SECRET_NAME>)
# API_KEY = "your-api-key"
# API_KEY_ID = "your-api-key-id"  
# ORG_ID = "your-organization-id"
# SIGNALS_API_URL = "https://your-signals-endpoint.signals.snowplowanalytics.com"

# KV namespace for caching auth tokens
[[kv_namespaces]]
binding = "AUTH_CACHE"
id = "7bcf15ad887445feaf309d72dfaa6bae"

[build]
command = "npm run build"

[env.production]
name = "signals-workshop-worker-prod"
compatibility_date = "2024-01-01"

[[env.production.kv_namespaces]]
binding = "AUTH_CACHE"
id = "7bcf15ad887445feaf309d72dfaa6bae"

[observability.logs]
enabled = true
